/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LegalTypeRouteImport } from './routes/legal.$type'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHotKeywordsIndexRouteImport } from './routes/_authenticated/hot-keywords/index'
import { Route as AuthenticatedContentIndexRouteImport } from './routes/_authenticated/content/index'
import { Route as AuthenticatedAiOpsIndexRouteImport } from './routes/_authenticated/ai-ops/index'
import { Route as AuthenticatedActivitiesIndexRouteImport } from './routes/_authenticated/activities/index'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users/$id'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSafetyModerationRouteImport } from './routes/_authenticated/safety/moderation'
import { Route as AuthenticatedSafetyActivitiesRouteImport } from './routes/_authenticated/safety/activities'
import { Route as AuthenticatedHotKeywordsCreateRouteImport } from './routes/_authenticated/hot-keywords/create'
import { Route as AuthenticatedHotKeywordsAnalyticsRouteImport } from './routes/_authenticated/hot-keywords/analytics'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedContentIdRouteImport } from './routes/_authenticated/content/$id'
import { Route as AuthenticatedAiOpsUsageRouteImport } from './routes/_authenticated/ai-ops/usage'
import { Route as AuthenticatedAiOpsPlaygroundRouteImport } from './routes/_authenticated/ai-ops/playground'
import { Route as AuthenticatedAiOpsConversationsRouteImport } from './routes/_authenticated/ai-ops/conversations'
import { Route as AuthenticatedAiOpsConfigRouteImport } from './routes/_authenticated/ai-ops/config'
import { Route as AuthenticatedActivitiesIdRouteImport } from './routes/_authenticated/activities/$id'
import { Route as AuthenticatedHotKeywordsIdEditRouteImport } from './routes/_authenticated/hot-keywords/$id.edit'
import { Route as AuthenticatedAiOpsSecurityModerationRouteImport } from './routes/_authenticated/ai-ops/security/moderation'
import { Route as AuthenticatedAiOpsConversationsIdRouteImport } from './routes/_authenticated/ai-ops/conversations.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegalTypeRoute = LegalTypeRouteImport.update({
  id: '/legal/$type',
  path: '/legal/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHotKeywordsIndexRoute =
  AuthenticatedHotKeywordsIndexRouteImport.update({
    id: '/hot-keywords/',
    path: '/hot-keywords/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentIndexRoute =
  AuthenticatedContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiOpsIndexRoute = AuthenticatedAiOpsIndexRouteImport.update({
  id: '/ai-ops/',
  path: '/ai-ops/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesIndexRoute =
  AuthenticatedActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSafetyModerationRoute =
  AuthenticatedSafetyModerationRouteImport.update({
    id: '/safety/moderation',
    path: '/safety/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSafetyActivitiesRoute =
  AuthenticatedSafetyActivitiesRouteImport.update({
    id: '/safety/activities',
    path: '/safety/activities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotKeywordsCreateRoute =
  AuthenticatedHotKeywordsCreateRouteImport.update({
    id: '/hot-keywords/create',
    path: '/hot-keywords/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotKeywordsAnalyticsRoute =
  AuthenticatedHotKeywordsAnalyticsRouteImport.update({
    id: '/hot-keywords/analytics',
    path: '/hot-keywords/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentIdRoute = AuthenticatedContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiOpsUsageRoute = AuthenticatedAiOpsUsageRouteImport.update({
  id: '/ai-ops/usage',
  path: '/ai-ops/usage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiOpsPlaygroundRoute =
  AuthenticatedAiOpsPlaygroundRouteImport.update({
    id: '/ai-ops/playground',
    path: '/ai-ops/playground',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiOpsConversationsRoute =
  AuthenticatedAiOpsConversationsRouteImport.update({
    id: '/ai-ops/conversations',
    path: '/ai-ops/conversations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiOpsConfigRoute =
  AuthenticatedAiOpsConfigRouteImport.update({
    id: '/ai-ops/config',
    path: '/ai-ops/config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivitiesIdRoute =
  AuthenticatedActivitiesIdRouteImport.update({
    id: '/activities/$id',
    path: '/activities/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotKeywordsIdEditRoute =
  AuthenticatedHotKeywordsIdEditRouteImport.update({
    id: '/hot-keywords/$id/edit',
    path: '/hot-keywords/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiOpsSecurityModerationRoute =
  AuthenticatedAiOpsSecurityModerationRouteImport.update({
    id: '/ai-ops/security/moderation',
    path: '/ai-ops/security/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiOpsConversationsIdRoute =
  AuthenticatedAiOpsConversationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAiOpsConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/legal/$type': typeof LegalTypeRoute
  '/': typeof AuthenticatedIndexRoute
  '/activities/$id': typeof AuthenticatedActivitiesIdRoute
  '/ai-ops/config': typeof AuthenticatedAiOpsConfigRoute
  '/ai-ops/conversations': typeof AuthenticatedAiOpsConversationsRouteWithChildren
  '/ai-ops/playground': typeof AuthenticatedAiOpsPlaygroundRoute
  '/ai-ops/usage': typeof AuthenticatedAiOpsUsageRoute
  '/content/$id': typeof AuthenticatedContentIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hot-keywords/analytics': typeof AuthenticatedHotKeywordsAnalyticsRoute
  '/hot-keywords/create': typeof AuthenticatedHotKeywordsCreateRoute
  '/safety/activities': typeof AuthenticatedSafetyActivitiesRoute
  '/safety/moderation': typeof AuthenticatedSafetyModerationRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/activities': typeof AuthenticatedActivitiesIndexRoute
  '/ai-ops': typeof AuthenticatedAiOpsIndexRoute
  '/content': typeof AuthenticatedContentIndexRoute
  '/hot-keywords': typeof AuthenticatedHotKeywordsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/ai-ops/conversations/$id': typeof AuthenticatedAiOpsConversationsIdRoute
  '/ai-ops/security/moderation': typeof AuthenticatedAiOpsSecurityModerationRoute
  '/hot-keywords/$id/edit': typeof AuthenticatedHotKeywordsIdEditRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/legal/$type': typeof LegalTypeRoute
  '/': typeof AuthenticatedIndexRoute
  '/activities/$id': typeof AuthenticatedActivitiesIdRoute
  '/ai-ops/config': typeof AuthenticatedAiOpsConfigRoute
  '/ai-ops/conversations': typeof AuthenticatedAiOpsConversationsRouteWithChildren
  '/ai-ops/playground': typeof AuthenticatedAiOpsPlaygroundRoute
  '/ai-ops/usage': typeof AuthenticatedAiOpsUsageRoute
  '/content/$id': typeof AuthenticatedContentIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hot-keywords/analytics': typeof AuthenticatedHotKeywordsAnalyticsRoute
  '/hot-keywords/create': typeof AuthenticatedHotKeywordsCreateRoute
  '/safety/activities': typeof AuthenticatedSafetyActivitiesRoute
  '/safety/moderation': typeof AuthenticatedSafetyModerationRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/activities': typeof AuthenticatedActivitiesIndexRoute
  '/ai-ops': typeof AuthenticatedAiOpsIndexRoute
  '/content': typeof AuthenticatedContentIndexRoute
  '/hot-keywords': typeof AuthenticatedHotKeywordsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/ai-ops/conversations/$id': typeof AuthenticatedAiOpsConversationsIdRoute
  '/ai-ops/security/moderation': typeof AuthenticatedAiOpsSecurityModerationRoute
  '/hot-keywords/$id/edit': typeof AuthenticatedHotKeywordsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/legal/$type': typeof LegalTypeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/activities/$id': typeof AuthenticatedActivitiesIdRoute
  '/_authenticated/ai-ops/config': typeof AuthenticatedAiOpsConfigRoute
  '/_authenticated/ai-ops/conversations': typeof AuthenticatedAiOpsConversationsRouteWithChildren
  '/_authenticated/ai-ops/playground': typeof AuthenticatedAiOpsPlaygroundRoute
  '/_authenticated/ai-ops/usage': typeof AuthenticatedAiOpsUsageRoute
  '/_authenticated/content/$id': typeof AuthenticatedContentIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/hot-keywords/analytics': typeof AuthenticatedHotKeywordsAnalyticsRoute
  '/_authenticated/hot-keywords/create': typeof AuthenticatedHotKeywordsCreateRoute
  '/_authenticated/safety/activities': typeof AuthenticatedSafetyActivitiesRoute
  '/_authenticated/safety/moderation': typeof AuthenticatedSafetyModerationRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
  '/_authenticated/activities/': typeof AuthenticatedActivitiesIndexRoute
  '/_authenticated/ai-ops/': typeof AuthenticatedAiOpsIndexRoute
  '/_authenticated/content/': typeof AuthenticatedContentIndexRoute
  '/_authenticated/hot-keywords/': typeof AuthenticatedHotKeywordsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/ai-ops/conversations/$id': typeof AuthenticatedAiOpsConversationsIdRoute
  '/_authenticated/ai-ops/security/moderation': typeof AuthenticatedAiOpsSecurityModerationRoute
  '/_authenticated/hot-keywords/$id/edit': typeof AuthenticatedHotKeywordsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/legal/$type'
    | '/'
    | '/activities/$id'
    | '/ai-ops/config'
    | '/ai-ops/conversations'
    | '/ai-ops/playground'
    | '/ai-ops/usage'
    | '/content/$id'
    | '/errors/$error'
    | '/hot-keywords/analytics'
    | '/hot-keywords/create'
    | '/safety/activities'
    | '/safety/moderation'
    | '/settings/account'
    | '/settings/appearance'
    | '/users/$id'
    | '/activities'
    | '/ai-ops'
    | '/content'
    | '/hot-keywords'
    | '/settings/'
    | '/users'
    | '/ai-ops/conversations/$id'
    | '/ai-ops/security/moderation'
    | '/hot-keywords/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/legal/$type'
    | '/'
    | '/activities/$id'
    | '/ai-ops/config'
    | '/ai-ops/conversations'
    | '/ai-ops/playground'
    | '/ai-ops/usage'
    | '/content/$id'
    | '/errors/$error'
    | '/hot-keywords/analytics'
    | '/hot-keywords/create'
    | '/safety/activities'
    | '/safety/moderation'
    | '/settings/account'
    | '/settings/appearance'
    | '/users/$id'
    | '/activities'
    | '/ai-ops'
    | '/content'
    | '/hot-keywords'
    | '/settings'
    | '/users'
    | '/ai-ops/conversations/$id'
    | '/ai-ops/security/moderation'
    | '/hot-keywords/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/legal/$type'
    | '/_authenticated/'
    | '/_authenticated/activities/$id'
    | '/_authenticated/ai-ops/config'
    | '/_authenticated/ai-ops/conversations'
    | '/_authenticated/ai-ops/playground'
    | '/_authenticated/ai-ops/usage'
    | '/_authenticated/content/$id'
    | '/_authenticated/errors/$error'
    | '/_authenticated/hot-keywords/analytics'
    | '/_authenticated/hot-keywords/create'
    | '/_authenticated/safety/activities'
    | '/_authenticated/safety/moderation'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/users/$id'
    | '/_authenticated/activities/'
    | '/_authenticated/ai-ops/'
    | '/_authenticated/content/'
    | '/_authenticated/hot-keywords/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/ai-ops/conversations/$id'
    | '/_authenticated/ai-ops/security/moderation'
    | '/_authenticated/hot-keywords/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  LegalTypeRoute: typeof LegalTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legal/$type': {
      id: '/legal/$type'
      path: '/legal/$type'
      fullPath: '/legal/$type'
      preLoaderRoute: typeof LegalTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/hot-keywords/': {
      id: '/_authenticated/hot-keywords/'
      path: '/hot-keywords'
      fullPath: '/hot-keywords'
      preLoaderRoute: typeof AuthenticatedHotKeywordsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/': {
      id: '/_authenticated/content/'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-ops/': {
      id: '/_authenticated/ai-ops/'
      path: '/ai-ops'
      fullPath: '/ai-ops'
      preLoaderRoute: typeof AuthenticatedAiOpsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/': {
      id: '/_authenticated/activities/'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/safety/moderation': {
      id: '/_authenticated/safety/moderation'
      path: '/safety/moderation'
      fullPath: '/safety/moderation'
      preLoaderRoute: typeof AuthenticatedSafetyModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety/activities': {
      id: '/_authenticated/safety/activities'
      path: '/safety/activities'
      fullPath: '/safety/activities'
      preLoaderRoute: typeof AuthenticatedSafetyActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hot-keywords/create': {
      id: '/_authenticated/hot-keywords/create'
      path: '/hot-keywords/create'
      fullPath: '/hot-keywords/create'
      preLoaderRoute: typeof AuthenticatedHotKeywordsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hot-keywords/analytics': {
      id: '/_authenticated/hot-keywords/analytics'
      path: '/hot-keywords/analytics'
      fullPath: '/hot-keywords/analytics'
      preLoaderRoute: typeof AuthenticatedHotKeywordsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/$id': {
      id: '/_authenticated/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof AuthenticatedContentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-ops/usage': {
      id: '/_authenticated/ai-ops/usage'
      path: '/ai-ops/usage'
      fullPath: '/ai-ops/usage'
      preLoaderRoute: typeof AuthenticatedAiOpsUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-ops/playground': {
      id: '/_authenticated/ai-ops/playground'
      path: '/ai-ops/playground'
      fullPath: '/ai-ops/playground'
      preLoaderRoute: typeof AuthenticatedAiOpsPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-ops/conversations': {
      id: '/_authenticated/ai-ops/conversations'
      path: '/ai-ops/conversations'
      fullPath: '/ai-ops/conversations'
      preLoaderRoute: typeof AuthenticatedAiOpsConversationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-ops/config': {
      id: '/_authenticated/ai-ops/config'
      path: '/ai-ops/config'
      fullPath: '/ai-ops/config'
      preLoaderRoute: typeof AuthenticatedAiOpsConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities/$id': {
      id: '/_authenticated/activities/$id'
      path: '/activities/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof AuthenticatedActivitiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hot-keywords/$id/edit': {
      id: '/_authenticated/hot-keywords/$id/edit'
      path: '/hot-keywords/$id/edit'
      fullPath: '/hot-keywords/$id/edit'
      preLoaderRoute: typeof AuthenticatedHotKeywordsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-ops/security/moderation': {
      id: '/_authenticated/ai-ops/security/moderation'
      path: '/ai-ops/security/moderation'
      fullPath: '/ai-ops/security/moderation'
      preLoaderRoute: typeof AuthenticatedAiOpsSecurityModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-ops/conversations/$id': {
      id: '/_authenticated/ai-ops/conversations/$id'
      path: '/$id'
      fullPath: '/ai-ops/conversations/$id'
      preLoaderRoute: typeof AuthenticatedAiOpsConversationsIdRouteImport
      parentRoute: typeof AuthenticatedAiOpsConversationsRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedAiOpsConversationsRouteChildren {
  AuthenticatedAiOpsConversationsIdRoute: typeof AuthenticatedAiOpsConversationsIdRoute
}

const AuthenticatedAiOpsConversationsRouteChildren: AuthenticatedAiOpsConversationsRouteChildren =
  {
    AuthenticatedAiOpsConversationsIdRoute:
      AuthenticatedAiOpsConversationsIdRoute,
  }

const AuthenticatedAiOpsConversationsRouteWithChildren =
  AuthenticatedAiOpsConversationsRoute._addFileChildren(
    AuthenticatedAiOpsConversationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedActivitiesIdRoute: typeof AuthenticatedActivitiesIdRoute
  AuthenticatedAiOpsConfigRoute: typeof AuthenticatedAiOpsConfigRoute
  AuthenticatedAiOpsConversationsRoute: typeof AuthenticatedAiOpsConversationsRouteWithChildren
  AuthenticatedAiOpsPlaygroundRoute: typeof AuthenticatedAiOpsPlaygroundRoute
  AuthenticatedAiOpsUsageRoute: typeof AuthenticatedAiOpsUsageRoute
  AuthenticatedContentIdRoute: typeof AuthenticatedContentIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHotKeywordsAnalyticsRoute: typeof AuthenticatedHotKeywordsAnalyticsRoute
  AuthenticatedHotKeywordsCreateRoute: typeof AuthenticatedHotKeywordsCreateRoute
  AuthenticatedSafetyActivitiesRoute: typeof AuthenticatedSafetyActivitiesRoute
  AuthenticatedSafetyModerationRoute: typeof AuthenticatedSafetyModerationRoute
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
  AuthenticatedActivitiesIndexRoute: typeof AuthenticatedActivitiesIndexRoute
  AuthenticatedAiOpsIndexRoute: typeof AuthenticatedAiOpsIndexRoute
  AuthenticatedContentIndexRoute: typeof AuthenticatedContentIndexRoute
  AuthenticatedHotKeywordsIndexRoute: typeof AuthenticatedHotKeywordsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAiOpsSecurityModerationRoute: typeof AuthenticatedAiOpsSecurityModerationRoute
  AuthenticatedHotKeywordsIdEditRoute: typeof AuthenticatedHotKeywordsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedActivitiesIdRoute: AuthenticatedActivitiesIdRoute,
  AuthenticatedAiOpsConfigRoute: AuthenticatedAiOpsConfigRoute,
  AuthenticatedAiOpsConversationsRoute:
    AuthenticatedAiOpsConversationsRouteWithChildren,
  AuthenticatedAiOpsPlaygroundRoute: AuthenticatedAiOpsPlaygroundRoute,
  AuthenticatedAiOpsUsageRoute: AuthenticatedAiOpsUsageRoute,
  AuthenticatedContentIdRoute: AuthenticatedContentIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHotKeywordsAnalyticsRoute:
    AuthenticatedHotKeywordsAnalyticsRoute,
  AuthenticatedHotKeywordsCreateRoute: AuthenticatedHotKeywordsCreateRoute,
  AuthenticatedSafetyActivitiesRoute: AuthenticatedSafetyActivitiesRoute,
  AuthenticatedSafetyModerationRoute: AuthenticatedSafetyModerationRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedActivitiesIndexRoute: AuthenticatedActivitiesIndexRoute,
  AuthenticatedAiOpsIndexRoute: AuthenticatedAiOpsIndexRoute,
  AuthenticatedContentIndexRoute: AuthenticatedContentIndexRoute,
  AuthenticatedHotKeywordsIndexRoute: AuthenticatedHotKeywordsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAiOpsSecurityModerationRoute:
    AuthenticatedAiOpsSecurityModerationRoute,
  AuthenticatedHotKeywordsIdEditRoute: AuthenticatedHotKeywordsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  LegalTypeRoute: LegalTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
