#!/usr/bin/env bun

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(SCRIPT_DIR, "..");
const SOURCE_PROTOCOL = resolve(
  ROOT,
  "packages/genui-contract/src/protocol.ts"
);
const SOURCE_SCHEMAS = [
  "request.schema.json",
  "response-envelope.schema.json",
  "stream-event.schema.json",
];

const TARGETS = [
  resolve(ROOT, "apps/web/src/gen/genui-contract.ts"),
  resolve(ROOT, "apps/miniprogram/src/gen/genui-contract.ts"),
];

const TARGET_SCHEMA_DIRS = [
  resolve(ROOT, "apps/web/src/gen/schemas"),
  resolve(ROOT, "apps/miniprogram/src/gen/schemas"),
];

const GENERATED_HEADER = `// AUTO-GENERATED by scripts/gen-genui-contract.ts.
// DO NOT EDIT MANUALLY.

`;

async function writeGeneratedContractFiles() {
  const protocolSource = await readFile(SOURCE_PROTOCOL, "utf8");

  await Promise.all(
    TARGETS.map(async (targetFile) => {
      await mkdir(dirname(targetFile), { recursive: true });
      await writeFile(targetFile, `${GENERATED_HEADER}${protocolSource}`, "utf8");
    })
  );
}

async function writeGeneratedSchemas() {
  await Promise.all(
    TARGET_SCHEMA_DIRS.flatMap((targetDir) =>
      SOURCE_SCHEMAS.map(async (schemaName) => {
        const source = resolve(ROOT, "packages/genui-contract/schema", schemaName);
        const target = resolve(targetDir, schemaName);
        const content = await readFile(source, "utf8");
        await mkdir(dirname(target), { recursive: true });
        await writeFile(target, content, "utf8");
      })
    )
  );
}

async function main() {
  await writeGeneratedContractFiles();
  await writeGeneratedSchemas();

  console.log("GenUI contract generated successfully.");
  for (const target of TARGETS) {
    console.log(`- ${target}`);
  }
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`Failed to generate GenUI contract: ${message}`);
  process.exit(1);
});
